# Generated by Django 3.2.3 on 2021-07-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Semester', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division_m',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=30, unique=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='Course.course_m')),
                ('semester_id', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='Semester.semester_m')),
            ],
            options={
                'db_table': 'division_m',
            },
        ),
    ]
