# Generated by Django 3.2.3 on 2021-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Division', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division_m',
            name='division_name',
            field=models.CharField(max_length=30),
        ),
    ]
