# Generated by Django 3.2.3 on 2021-07-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_m',
            name='semester_name',
            field=models.CharField(max_length=30),
        ),
    ]
