# Generated by Django 3.2.3 on 2021-07-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(error_messages={'email': 'Please Enter Valid Email!!'}, max_length=50, unique=True)),
                ('enrollment_number', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True, unique=True)),
                ('course_name', models.CharField(max_length=30)),
                ('semester_name', models.CharField(max_length=30)),
                ('division_name', models.CharField(max_length=30)),
                ('batch_name', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extendeduser',
            },
        ),
    ]
