# Generated by Django 3.2.3 on 2021-07-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='subject_name',
            new_name='elective_subject',
        ),
    ]
