# Generated by Django 3.2.3 on 2021-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_subject_name_extendeduser_elective_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='batch_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='course_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='division_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='elective_subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='semester_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
