# Generated by Django 3.2.3 on 2021-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210720_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='enrollment_number',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
