# Generated by Django 3.2.3 on 2021-07-19 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Semester', '0001_initial'),
        ('Batch', '0001_initial'),
        ('Subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_m',
            fields=[
                ('fact_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='Batch.batch_m')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='Course.course_m')),
                ('faculty_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester_id', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='Semester.semester_m')),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='Subject.subject_m')),
            ],
            options={
                'db_table': 'faculty_m',
            },
        ),
    ]
