# Generated by Django 3.2.3 on 2021-07-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty_Subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty_m',
            table='faculty_subject_m',
        ),
    ]
