# Generated by Django 3.2.3 on 2021-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0002_subject_m_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_m',
            name='subject_type',
            field=models.CharField(max_length=30),
        ),
    ]
